### ISSUE TITLE
How to use your code for doing some other experiments?

### ISSUE THREAD

**Issue by Mah-Zam** [balachander27/FEBA#1]
Hello Balachander,
I reviewed your paper and got interested to use your code and doing new experiments with other datasets. Could you please guide me with usage of your code (how to execute)? Thanks

**Comment by balachander27** [comment]
Hey there Mah-Zam,
I have added the example notebooks on how to use my code.

**Comment by balachander27** [comment]
Hey there Mah-Zam,
I have added the example notebooks on how to use my code.
